version: '3'

networks:
  wordpress:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./wordpress:/var/www/html:delegated
    depends_on:
      - php
      - mysql
    networks:
      - wordpress

  mysql:
    image: mysql:oracle
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - wordpress
    volumes: 
      - ./mysql:/var/lib/mysql:delegated
    user: mysql

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./wordpress:/var/www/html:delegated
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - wordpress

  wp:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: wp
    entrypoint: ['wp', '--allow-root']
    environment:
      - PHP_EXTENSION_XDEBUG=1
    volumes:
      - ./wordpress:/var/www/html:delegated
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - wordpress

  phpmyadmin:
    depends_on:
      - mysql
      - php
      - wp
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      MYSQL_USER: mysql
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - wordpress